### ISSUE TITLE
Is this project being dropped?

### ISSUE THREAD

**Issue by Girnade** [wcolding/TWW-Coop#1]
I think this idea could be ground breaking in the windwaker randomizer community. There are a lot of talented individuals within the Wind Waker Randomizer Discord server that you could even find help on. I can see this gaining a lot of popularity if you can put out a working build!

**Comment by Sophilautia** [comment]
+1, really hoping to see this finished as I'd love to play Wind Waker Randomizer co-op runs with friends using this.

**Comment by wcolding** [comment]
This version of the co-op is being shelved, as the Modloader64 folks were working on WW Online. With how well OoT and MM Online work I opted to leave it in their capable hands.

However, I have begun been refactoring this code privately to work as an Archipelago client for use in multiworld/multigame sessions. I am also detaching it from a specific Dolphin build and having it hook externally instead.

I have a way of detecting a player getting various checks and making this work with the AP C# client API, but there is a lot to do and life has been busy. Plus, I am relatively inexperienced with the ROM/ISO patching side of things. So don't expect anything this year honestly.

**Comment by wcolding** [comment]
This version does sync inventory though. It doesn't properly do game state syncing unfortunately. I got hung up on making that work. Maybe I can put together a basic build soon with just the inventory stuff. But I am moving soon and my computer has been packed away. Maybe in September!

**Comment by Girnade** [comment]
Thanks for the info and I hope your move goes smoothly!

**Comment by wcolding** [comment]
Necro-ing this to inform you that Modloader64 does appear to have nightly dolphin builds with Wind Waker Online if you want to try it out. I have not yet but it is definitely more robust than anything I was doing.
